FROM python:3.8.0-slim
LABEL maintainer="Lanjelin"
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y \
        gcc \
        git \
        wget && \
    git clone https://github.com/revoxhere/duino-coin && \
    wget -qO /entrypoint.sh https://raw.githubusercontent.com/Lanjelin/docker-tinker/main/duinocoin/entrypoint.sh && \
    chmod +x entrypoint.sh && \
    cd duino-coin && \
    python3 -m pip install -r requirements.txt
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
