version: "3.9"
services:
    DuinoCoinAVR:
        container_name: DuinoCoinAVR
        image: duinocoin:latest
        restart: unless-stopped
        environment:
          username: lanjelin
          ident: DockerUNO
          mode: AVR
          devices: /dev/ttyUSB0,/dev/ttyUSB1,/dev/ttyUSB2,/dev/ttyUSB3,/dev/ttyACM0,/dev/ttyACM1
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
          - "/dev/ttyUSB1:/dev/ttyUSB1"
          - "/dev/ttyUSB2:/dev/ttyUSB2"
          - "/dev/ttyUSB3:/dev/ttyUSB3"
          - "/dev/ttyACM0:/dev/ttyACM0"
          - "/dev/ttyACM1:/dev/ttyACM1"
    DuinoCoinPC:
        container_name: DuinoCoinPC
        image: duinocoin:latest
        restart: unless-stopped
        environment:
          username: lanjelin
          threads: 4
          intensity: 100
          diff: LOW
          ident: DockerPi4
